//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbfirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriBilgisi
    {
        public int Id { get; set; }
        public Nullable<int> AliciId { get; set; }
        public Nullable<int> GondericiId { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
    }
}
