//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbfirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string SoyAd { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SubeId { get; set; }
        public string Yetki { get; set; }
    }
}
